// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvje5wMH6wGWJa4c0S9_PXZ3XIazToq0',
    appId: '1:456751401776:web:55ac0c519cc3a77c1296f5',
    messagingSenderId: '456751401776',
    projectId: 'health-hive-1',
    authDomain: 'health-hive-1.firebaseapp.com',
    storageBucket: 'health-hive-1.appspot.com',
    measurementId: 'G-0VTZ1SLWFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNP43jl3749-wJExn0NEJocZ1T0gCW0CU',
    appId: '1:456751401776:android:e2ecb4b835c653321296f5',
    messagingSenderId: '456751401776',
    projectId: 'health-hive-1',
    storageBucket: 'health-hive-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_HMVbdC9yly_2ze2Ms7xR5_pf_ugQbQ',
    appId: '1:456751401776:ios:3a925cd3831323cd1296f5',
    messagingSenderId: '456751401776',
    projectId: 'health-hive-1',
    storageBucket: 'health-hive-1.appspot.com',
    iosBundleId: 'com.example.healthHiveDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_HMVbdC9yly_2ze2Ms7xR5_pf_ugQbQ',
    appId: '1:456751401776:ios:3be32137bb208f501296f5',
    messagingSenderId: '456751401776',
    projectId: 'health-hive-1',
    storageBucket: 'health-hive-1.appspot.com',
    iosBundleId: 'com.example.healthHiveDoc.RunnerTests',
  );
}
